module.exports = {
  apps: [
    {
      name: 'funding-fee-program',
      script: 'scripts/start-standalone.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      autorestart: true,
      min_uptime: '20s',
      max_restarts: 50,
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      kill_timeout: 10000,
      max_memory_restart: '700M',
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
      },
    },
    {
      name: 'funding-fee-watchdog',
      script: 'scripts/runtime-watchdog.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      autorestart: true,
      min_uptime: '20s',
      max_restarts: 50,
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      kill_timeout: 5000,
      env: {
        NODE_ENV: 'production',
        WATCHDOG_BASE_URL: 'http://127.0.0.1:3000',
        WATCHDOG_TARGET_PROCESS: 'funding-fee-program',
        WATCHDOG_INTERVAL_MS: '20000',
        WATCHDOG_HTTP_TIMEOUT_MS: '10000',
        WATCHDOG_APP_FAIL_THRESHOLD: '3',
        WATCHDOG_DATA_FAIL_THRESHOLD: '6',
        WATCHDOG_STARTUP_GRACE_MS: '90000',
        WATCHDOG_RESTART_COOLDOWN_MS: '300000',
        WATCHDOG_DATA_PROBE_INTERVAL_MS: '60000',
        WATCHDOG_FUNDING_STALL_THRESHOLD_MS: '1200000',
      },
    },
  ],
};
