module.exports = {
  apps: [
    {
      name: 'funding-fee-program',
      script: 'scripts/start-standalone.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      autorestart: true,
      min_uptime: '20s',
      max_restarts: 50,
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      kill_timeout: 10000,
      max_memory_restart: '2G',
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
        SITE_PASSWORD: process.env.SITE_PASSWORD || '9788',
        INTERNAL_API_TOKEN: process.env.INTERNAL_API_TOKEN || process.env.SITE_PASSWORD || '9788',
        // Scenario D guard relaxation flags. Default OFF when env unset.
        // Read live by lib/relaxGuardsConfig.ts each scheduler tick, so
        // `pm2 reload ecosystem.config.cjs --update-env` flips behaviour.
        RELAX_FUNDING_WINDOW: process.env.RELAX_FUNDING_WINDOW || 'false',
        ORDERBOOK_DEFER_ENABLED: process.env.ORDERBOOK_DEFER_ENABLED || 'false',
      },
    },
    {
      name: 'funding-fee-watchdog',
      script: 'scripts/runtime-watchdog.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      autorestart: true,
      min_uptime: '20s',
      max_restarts: 50,
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      kill_timeout: 5000,
      env: {
        NODE_ENV: 'production',
        WATCHDOG_BASE_URL: 'http://127.0.0.1:3000',
        WATCHDOG_TARGET_PROCESS: 'funding-fee-program',
        WATCHDOG_INTERVAL_MS: '20000',
        WATCHDOG_HTTP_TIMEOUT_MS: '10000',
        WATCHDOG_INTERNAL_API_TOKEN: process.env.WATCHDOG_INTERNAL_API_TOKEN || process.env.INTERNAL_API_TOKEN || process.env.SITE_PASSWORD || '9788',
        WATCHDOG_APP_FAIL_THRESHOLD: '3',
        WATCHDOG_DATA_FAIL_THRESHOLD: '3',
        WATCHDOG_STARTUP_GRACE_MS: '90000',
        WATCHDOG_RESTART_COOLDOWN_MS: '120000',
        WATCHDOG_DATA_PROBE_INTERVAL_MS: '20000',
        WATCHDOG_FUNDING_STALL_THRESHOLD_MS: '60000',
        // real | sim | both | either(default)
        WATCHDOG_EXPECTED_MODE: 'either',
      },
    },
  ],
};
